version: '3.4'

services:
  devfolio:
    image: devfolio
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 9000:9000
